@startuml case3

participant human AS h
participant computer as c
participant drive as d

h -> c : запрос записи информации\n \t\t   на диск
c -> d : запись не выполнена,\n недостаточно памяти
d -> h : ручное освобожедние памяти
h -> c : повторный запрос
c -> d : успешная запись
@enduml