@startuml Activity
start
if (Система запущена?) then (yes)
    : Проверить работоспособность;
    kill;
else (no) 
    : Запустить систему;
    if (Все работает стабильно?) then (yes)
        : Составить лог файл;
        kill;
    else (no)
    : начать проверку;
        if(Выявлена проблема?) then (yes)
        : Решить проблему и восстановить работу систему;
        kill
        else (no)
        : Восстановить работу систему;
        kill
        endif
    endif
endif

@enduml