@startuml state

[*] --> ЗапускСистемы
ЗапускСистемы : Система запущена

ЗапускСистемы --> записьИнформации : Прошлое некоторе\nвремя

записьИнформации: Запись информации в лог файл

ЗапускСистемы --> АварийноеПоложение : Произошла критическая\nситуация
АварийноеПоложение: Что-то то произошло с\nрабочими станциями

АварийноеПоложение --> Расследование : Проведения расследования
Расследование: Исследование лог файлов\nс целью выяснения обстоятельств

Расследование --> Вывод: Результат расследования
Вывод: Подведение итогов причин\n возникновения проблем

Вывод --> ВосстановлениеСистемы: Восстановление работы системы
ВосстановлениеСистемы: Система функционирует как ожидается


записьИнформации --> НормальноеФункционирование: Проблем не найдено
НормальноеФункционирование: Проблем не выявлено
@enduml