@startuml usecase2

left to right direction
skinparam actorStyle awesome
:Пользователь: as user
:Администратор: as admin

package Admin{
    usecase "Настройка системы оповещения" as uc1
    usecase "Настройка рабочих станций" as uc2
    usecase "Формирование отчетов на основе\nлог файлов" as uc3
    usecase "Просмотр всех лог файлов за все время" as uc4
    usecase "Оповещение о возникновении\nВнештатных ситуаций" as uc41
}

admin --> uc1
admin --> uc2
admin --> uc3
admin --> uc4
admin --> uc41


package User{
    usecase "Просмотр определенных лог файлов" as uc5
    usecase "Отправка запросов к серверу" as uс6
    usecase "Прямой доступ к своей рабочей станции" as uc7
}

user --> uc5
user --> uс6
user --> uc7

 
@enduml