@startuml ATM
:Запросить карту и пароль;
if(пароль введен верно) then (да)
    #PaleGreen : разрешить доступ;
    :Запросить сумму для снятия;
     if(Денег достаточно) then (да)
     #PaleGreen : Выдать деньги;
     kill
     else (нет)
     #Pink : Выдать ошибку;
     kill
     endif
else (нет) 
    #Pink : Выдать ошибку;
    kill
endif

@endum